### ISSUE TITLE
Whiteboard - Voting being spammed

### ISSUE THREAD

**Issue by lee97matthew** [ngjunkang/classify#1]
I managed to get the voting comment to go negative by spamming the upvote button oops.
Seems to happen on the main thread as well, but takes awhile to update.

![image](https://user-images.githubusercontent.com/79011015/126812748-58feee30-c50a-4204-94f3-2a4a7a842a0d.png)

**Comment by pyk595** [comment]
upvote spamming disabled, thank you!
